### ISSUE TITLE
Agregar nuevamente mensaje de error en título de contacto

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#122]
Sale el error destacado, sin embargo no sale el mensaje que salía antes al lado de contacto para mostrar que en ese acordeón hay un error
![unnamed image 5](https://cloud.githubusercontent.com/assets/475834/16094182/0e7eb630-330d-11e6-9427-d09e80e79ffc.png)

**Comment by cltorresfe** [comment]
Oka @alagos , lo dejé en el PR #124
