### ISSUE TITLE
Crear página de perfil para información de un miembro

### ISSUE THREAD

**Issue by cltorresfe** [cltorresfe/members#145]
- Usar <a href="https://colorlib.com/polygon/gentelella/profile.html">este template.</a>
- En gráficos agregar Asistencia por ministerio.

**Comment by alagos** [comment]
@cltorresfe  ¿Como iría graficada la asistencia? mas bien, cuales serían los ejes **x** e **y**
¿Y que información específica piensas mostrar del usuario?

**Comment by alagos** [comment]
@cltorresfe otra cosa, entonces al hacer clic en un miembro, iría a esta página, ¿cierto? ¿Como se editaría el miembro luego? ¿Habría un botón para editar en esta vista o en la lista de miembros? ¿o en ambos?

**Comment by cltorresfe** [comment]
@alter pensaba hacer las barras que tiene el template con el porcentaje de asistencia histórico por ministerio.

Algo así...
![captura de pantalla 2016-06-23 a las 1 49 10 p m](https://cloud.githubusercontent.com/assets/10885198/16313903/5886084a-3949-11e6-8906-df0796270d71.png)

**Comment by cltorresfe** [comment]
La idea es mostrar toda la información del miembro y por supuesto tener un botón de editar. Ahora, tenemos que acordar si dejar tal cual como está ahora  el listado de miembros y agregar un lápiz como al principio para editar y para el link de la imagen "ver detalles" dirigir a la info/show del miembro.

![captura de pantalla 2016-06-23 a las 1 59 21 p m](https://cloud.githubusercontent.com/assets/10885198/16314193/be93f79a-394a-11e6-84d2-111678302c84.png)

**Comment by alagos** [comment]
> @alter pensaba hacer las barras que tiene el template con el porcentaje de asistencia histórico por ministerio.

Ah ok, pensé que usarías el gráfico grande que salía en el lado derecho del template.

> La idea es mostrar toda la información del miembro y por supuesto tener un botón de editar. Ahora, tenemos que acordar si dejar tal cual como está ahora el listado de miembros y agregar un lápiz como al principio para editar y para el link de la imagen "ver detalles" dirigir a la info/show del miembro.

Me da un poco de miedo que el botón de editar y borrar estén tan juntos, por el que se pueda borrar por accidente, de repente podría moverse o sacarse el de borrar. De hecho pensaba que incluso se podría sacar ambos botones y que solo se pueda acceder a editar/borrar al ver los detalles de un miembro. ¿opiniones?

**Comment by cltorresfe** [comment]
Si, tmbn pienso lo mismo. Podemos sacarlo y dejarlo solo en la vista de detalles.
