### ISSUE TITLE
Probar houndci

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#149]
@cltorresfe ¿podrías crear una cuenta en este servicio y agregar el proyecto? https://houndci.com 
Me gustaría probar el servicio y ver que hace, al parecer revisa errores de estilo en el código, onda buenas prácticas y eso. Al parecer es parecido a lo que tenemos actualmente con [Codeclimate](https://codeclimate.com/github/cltorresfe/members), pero comenta automáticamente aquí mismo en github. Bueno, es gratis, así que no hace daño probarlo :stuck_out_tongue:

**Comment by alagos** [comment]
mmmm, no, me arrepentí, después de los 15 correos que recibí por los cambios de [aquí](https://github.com/cltorresfe/members/pull/152), creo que no me gustó. Son detalles de estilo de codificación que hacen mas ruido que lo que de verdad aporten al proyecto. Creo que lo que tenemos con codeclimate es suficiente. Cerrando

**Comment by alagos** [comment]
ahhhh @cltorresfe y se me olvidó decirte, que desactives el servicio porfa.
Que quede abierto este issue hasta que haya sido cerrado

**Comment by cltorresfe** [comment]
oka. listo
