### ISSUE TITLE
Mostrar miembros de familia en vista de mostrar miembro

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#170]
- [x] En vista show de miembros, si un miembro tiene familia, mostrar:
  - [x] Nombre de la familia
  - [x] Todos los integrantes de dicha familia.
- [x] Los integrantes de la familia se mostrarán con el mismo formato que en la lista de miembros, además mostrando el rol que cumplen dichos miembros en la familia.

**Comment by cltorresfe** [comment]
![captura de pantalla 2016-07-28 a las 5 24 23 p m](https://cloud.githubusercontent.com/assets/10885198/17230036/4d857b46-54e8-11e6-8546-cbebb35b8102.png)
![captura de pantalla 2016-07-28 a las 5 24 46 p m](https://cloud.githubusercontent.com/assets/10885198/17230044/54c64d2c-54e8-11e6-9c1d-cb46e82982be.png)
