### ISSUE TITLE
Agregar badges al listado de miembros con estados pasivos 

### ISSUE THREAD

**Issue by cltorresfe** [cltorresfe/members#175]
los estados pasivos pueden ser:
- Transladado
- Inactivos
- Fallecidos

![captura de pantalla 2016-07-29 a las 12 46 41 a m](https://cloud.githubusercontent.com/assets/10885198/17238007/fb991d40-5525-11e6-8ba6-495f9d3b1103.png)

**Comment by alagos** [comment]
Se ve bonito, pero igual me queda algo dando vuelta como que es mucho texto
Lo otro, ¿que significaría en la práctica que uno de los miembros esté en estado pasivo?¿cambia en algo su comportamiento en esta etapa en algunas pantalla o aún no?

**Comment by cltorresfe** [comment]
debería cambiar...Ya que en los demás listados, como.. los miembros por ministerio o por responsabilidad no es necesario mostrar a los miembros que están pasivos.

**Comment by cltorresfe** [comment]
También podríamos agregar otro link en el menú "Listado de Miembros Pasivos" mostrando el estado de cada uno con un badge y en los demás listados de miembros no deberían mostrarse los miembros pasivos.
