### ISSUE TITLE
Enviar correo de asistencia/inasistencia por fecha al momento de crear/editar asistencia.

### ISSUE THREAD

**Issue by cltorresfe** [cltorresfe/members#36]
-  [x] Agregar al correo  % de asistencia.
-  [x] Agregar al correo un listado de asistentes/inasistentes con su número de teléfono.
-  [ ] Enviar correo con los datos al PDF adjunto.

**Comment by cltorresfe** [comment]
- [ ] Crear un PDF con % de asistencia por responsabilidad y total.
- [ ] Agregar al PDF listado de inasistentes con su número de teléfono.
- [ ] Enviar correo con el PDF adjunto.

**Comment by alagos** [comment]
Cerrando y agregando pdf adjunto a cosas por hacer de trello
