### ISSUE TITLE
Mejorar manejo de locale en url

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#43]
Deberia usarse algo mas piola que `?locale=es` en cada url. O simplemente sacarlo mientras no se implemente definitivamente

**Comment by alagos** [comment]
@cltorresfe algún feedback en esto? te parece? no?

**Comment by cltorresfe** [comment]
pienso que hay q sacar ese "?locale" y agregarle como va a quedar definitivamente

**Comment by cltorresfe** [comment]
una cosa como: " http:aplicación.com/es/miembros"

**Comment by alagos** [comment]
Por el momento que sea sacar el locale y en #69 se definirá con que seguir
