### ISSUE TITLE
Agregar gráficos en pantalla principal

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#44]
El nuevo template trae http://morrisjs.github.io/morris.js/ , podriamos usarlo para la generacion de graficos

**Comment by cltorresfe** [comment]
Está buenisimo

**Comment by cltorresfe** [comment]
- [x] Agregar indicador de miembros
- [x] Agregar indicador de Familias
- [x] Agregar gráfico de torta de miembros por grupo etáreo
- [x] Agregar gráfico por sexo
- [x] Agregar gráfico de últimas asistencia a ministerios
- [x] Agregar panel de los ultimos miembros agregados
- [x] Agregar panel de las ultimas familias agregadas
- [x] Agregar panel para aviso de cumpleaños
- [x] Agregar panel para aviso de aniversario de matrimonios.

**Comment by alagos** [comment]
@cltorresfe ¿esto iría incluido en #86 o va a ser aparte?

**Comment by cltorresfe** [comment]
@alagos lo dejé a parte

**Comment by alagos** [comment]
ajajjajaja ok
