### ISSUE TITLE
Agregar mas campos a perfil de miembro

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#50]
Ciudad, pais, quizás agregar contacto de redes sociales. Tratar de copiar de otros sistemas similares a ver que piden.

**Comment by cltorresfe** [comment]
Agregar campos:
- [ ] RUN 
  - En el caso de Noruega, el RUN tiene un número de 11 dígitos fijos divididos en "DDMMAAZZZZZ" donde: 
    - DD = día nacimiento. Ejemplo: "03"
    - MM= Mes de nacimiento 
    - AA = Año de Nacimiento
    - ZZZZZ = Número de 5 dígitos creados al azar.
- [ ] Sexo
- [ ] Testimonio
- [ ] Agregar Last Name
- [ ] Cambiar a First name
- [ ] Ciudad
- [ ] País
- [ ] Fecha nacimiento
- [ ] Fecha bautizmo
- [ ] Fecha membresía
- [ ] Fecha disciplina
- [ ] Fecha traslado
- [ ] Contacto facebook
- [ ] Contacto twitter
- [ ] Contacto skype

**Comment by alagos** [comment]
@cltorresfe también podría considerarse redes sociales, facebook, twitter, skype, etc
