### ISSUE TITLE
Crear Familia

### ISSUE THREAD

**Issue by cltorresfe** [cltorresfe/members#54]
- [x] campos en la tabla familia: 
1. Nombre Familia, 
2. fecha matrimonio
3. Dirección
4. Fono
5. Ciudad
6. País

**Comment by alagos** [comment]
Esto no involucra la asociación de miembros, eso se verá en #78

**Comment by alagos** [comment]
@cltorresfe acuerdate de cerrar los issues que referencien al PR que le hayas hecho merge
