### ISSUE TITLE
Integrar coveralls en el proyecto

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#58]
Es un servicio que te mide el test coverage que significa cuanto del codigo tenemos testeado y en este momento estamos bajos, pero podríamos estar peor, así que bien dentro de todo, jeje
![unnamed image 1](https://cloud.githubusercontent.com/assets/475834/15262144/df9f4c16-1936-11e6-8df8-f77ac0967144.png)
@cltorresfe ese reporte lo generé con una gema de test coverage llamada simplecov, revisa tu carpeta `coverage/` la próxima vez que corras los tests y ahí verás esa página.
https://coveralls.io/

**Comment by cltorresfe** [comment]
Está bien así @alagos ?
![captura de pantalla 2016-06-15 a las 4 42 30 p m](https://cloud.githubusercontent.com/assets/10885198/16096735/536999bc-3318-11e6-88c8-286f6cfc2135.png)

**Comment by alagos** [comment]
@cltorresfe Anda a https://coveralls.io/github/cltorresfe/members y busca el valor de `repo_token`, luego anda a https://circleci.com/gh/cltorresfe/members/edit#env-vars y agrega **name** `COVERALLS_REPO_TOKEN` y **value** el valor del token. Con eso y el PR #126 debería funcionar.

**Comment by cltorresfe** [comment]
Listo.
