### ISSUE TITLE
Validación del Ingreso de nuevo usuario 

### ISSUE THREAD

**Issue by cltorresfe** [cltorresfe/members#67]
Da error al ingresar ya que pide ingresar un nombre no vacío.

**Comment by cltorresfe** [comment]
@alagos este bug ya se solucionó en el Hotfix #88 ?

**Comment by alagos** [comment]
@cltorresfe sip, por? te sigue dando problemas?

**Comment by cltorresfe** [comment]
para cerrarlo.

**Comment by alagos** [comment]
Pero ya lo habías cerrado jaja
