### ISSUE TITLE
Asociar iglesia a usuario

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#89]
- [x] Al crear un usuario debe además pedir los datos de la iglesia en la cual participa. Para esto se debería pedir los mismos datos que se solicitan en la actual vista de creación de iglesias.
- [x] Sacar del sidebar el menu relacionado con crear iglesias

**Comment by cltorresfe** [comment]
Estaba pensando que en el sidebar deberíamos mantener sólo el listado de iglesias pero con la condicionan de si es super admin o no.
Si es super admin se listan todas las iglesias
Si es usuario común mostrar todos los gráficos relacionados a miembros, cargos y ministerios en esta pantalla. Sería como lo que pensábamos hacer en el index.

**Comment by alagos** [comment]
@cltorresfe al menos mi idea era que el super admin (que en realidad es admin a secas en primera instancia) pudiese ingresar a lo que puede un usuario normal + el acceso a active admin, que de ahí puede ver las iglesias. Si al final el super admin es algo que usaríamos nosotros y da un poco lo mismo que se muestren o no los datos con el formato del nuevo template

**Comment by cltorresfe** [comment]
PR #95
