### ISSUE TITLE
Refactoring de responsibilities

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#96]
Se debe definir si van a ser comunes para todos los usuarios, lo cual implicaría que no deberían poder crear nuevos, o si cada iglesia va a tener sus propios responsibilities.
Lo que se decida de aquí eventualmente implicaría cambiar el código también de [esto](https://github.com/cltorresfe/members/pull/95#discussion_r66320877) y [esto](https://github.com/cltorresfe/members/pull/95#discussion_r66320943)

**Comment by cltorresfe** [comment]
@alagos  Estuve pensando en esto después del bug #104 y es preferible que cada iglesia tenga sus propias responsabilidades. Esto pensando que más adelante será un sistema de al menos dos lenguajes.
